// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgzSrVQJTfUYLJLD_4t80Kq8KRpCzTpfM',
    appId: '1:359856036297:web:22de0293378839e6e7f018',
    messagingSenderId: '359856036297',
    projectId: 'fir-auth-78db3',
    authDomain: 'fir-auth-78db3.firebaseapp.com',
    storageBucket: 'fir-auth-78db3.appspot.com',
    measurementId: 'G-JQCQ173DP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzLEIw7dqItlHsXxEl81enBwKpIv05HOY',
    appId: '1:359856036297:android:93ec202a6cc7e08ce7f018',
    messagingSenderId: '359856036297',
    projectId: 'fir-auth-78db3',
    storageBucket: 'fir-auth-78db3.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgzSrVQJTfUYLJLD_4t80Kq8KRpCzTpfM',
    appId: '1:359856036297:web:5b71c747681d3104e7f018',
    messagingSenderId: '359856036297',
    projectId: 'fir-auth-78db3',
    authDomain: 'fir-auth-78db3.firebaseapp.com',
    storageBucket: 'fir-auth-78db3.appspot.com',
    measurementId: 'G-PRGRTZBE2C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArQF6_QSiw1nNJvfbde7SoDzeec4aFWJk',
    appId: '1:359856036297:ios:bfdeaaf697e2d603e7f018',
    messagingSenderId: '359856036297',
    projectId: 'fir-auth-78db3',
    storageBucket: 'fir-auth-78db3.appspot.com',
    iosBundleId: 'com.example.flutterFirebasePegionPost',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArQF6_QSiw1nNJvfbde7SoDzeec4aFWJk',
    appId: '1:359856036297:ios:bfdeaaf697e2d603e7f018',
    messagingSenderId: '359856036297',
    projectId: 'fir-auth-78db3',
    storageBucket: 'fir-auth-78db3.appspot.com',
    iosBundleId: 'com.example.flutterFirebasePegionPost',
  );

}