// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1TsfY5BF4YnwoCWjtLI5Ef3XxRqo8YbY',
    appId: '1:16824072976:web:a191afb9ad82e52d134395',
    messagingSenderId: '16824072976',
    projectId: 'socialmedia-cb33a',
    authDomain: 'socialmedia-cb33a.firebaseapp.com',
    storageBucket: 'socialmedia-cb33a.appspot.com',
    measurementId: 'G-R8TJR1GY6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2WByh7Kc-59ZjL3to3wAQFCdXd4zai8E',
    appId: '1:16824072976:android:1de764319d654a5d134395',
    messagingSenderId: '16824072976',
    projectId: 'socialmedia-cb33a',
    storageBucket: 'socialmedia-cb33a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1TsfY5BF4YnwoCWjtLI5Ef3XxRqo8YbY',
    appId: '1:16824072976:web:70684617287bed37134395',
    messagingSenderId: '16824072976',
    projectId: 'socialmedia-cb33a',
    authDomain: 'socialmedia-cb33a.firebaseapp.com',
    storageBucket: 'socialmedia-cb33a.appspot.com',
    measurementId: 'G-NNNGJ2MVW0',
  );

}